[graph]
all-features = true
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
